### ISSUE TITLE
Strip binary before packaging

### ISSUE THREAD

**Issue by apiraino** [barnumbirr/zola-debian#1]
hey @barnumbirr  thanks for building for Debian!

I was thinking if it would help slimming down a bit the size of the .deb by running `strip` on it, [maybe in this step](https://github.com/barnumbirr/zola-debian/blob/6587c801aff6b4ab3db975c4fee6c789054fdc3d/debian/rules#L10)? I'm not familiar with Debian package building so I'm not sure this would be the "canonical" way of doing it.

As of zola 0.13 the x86_64 binary size goes from ~26mb to ~21mb

**Comment by barnumbirr** [comment]
Hey there,

this has been fixed in v0.13.0-2 though I didn't see any size difference.

Cheers.

**Comment by apiraino** [comment]
thanks for the quick feedback. I've cloned this repository and run `./build.sh` before and after https://github.com/barnumbirr/zola-debian/commit/8375076f2734a6067c3101309d813f7e3a084cb5. The resulting Debian package contains a stripped binary, that's why the size difference is negligible.

Perhaps the stripping happens automatically somewhere in the package building process?
