### ISSUE TITLE
deb for arm64 architecture ? 

### ISSUE THREAD

**Issue by jalsco** [barnumbirr/zola-debian#2]
Hello,
thanks for providing these wonderful resources to use Zola. 
Are there `deb` files available for `arm64` architecture ? or only for `amd64` ?

**Comment by barnumbirr** [comment]
Hi,

packages are only available for `amd64` at this time as I've not taken the time to look into multi-arch Docker builds on Github Actions.

**Comment by jalsco** [comment]
ok... Thanks also for the super fast reply 😊
Actually am not using Docker - but I don't think that changes anything..  🤷🏻‍♂️

**Comment by barnumbirr** [comment]
You can probably get away with building the image manually for now.
Set the required environment variable as follows:

```bash
$ export DOCKER_DEFAULT_PLATFORM=linux/arm64
```

and edit the [`Architecture` in the Debian contril file to](https://github.com/barnumbirr/zola-debian/blob/master/debian/control#L14)

```yaml
Architecture: arm64
```
I've not tested this myself so you might need to play with Docker to get it to use the `arm64` but this should get you started.

Cheers.

**Comment by jalsco** [comment]
Will that manual build only work with `Docker` ?

**Comment by barnumbirr** [comment]
`Docker` is hardcoded in `build.sh` but should work with `podman` and the likes.

**Comment by jalsco** [comment]
Hi @barnumbirr Thank your for your guidance on this ...  But,  i tried my best - and I failed.... I tried at least a dozen times.  Each time took many hours - loading/installing 380+ software packages, eventually Rust gets installed and it starts compiling....  every single attempt failed to complete and did not produce the `deb`.  The attempt that got the furthest....  these were the last messages - before it abruptly stopped... 

```
   Compiling regex v1.6.0
   Compiling minify-js v0.1.5
   Compiling threadpool v1.8.1
   Compiling nanorand v0.7.0
   Compiling rand_core v0.6.3
   Compiling parking_lot v0.12.1
   Compiling bytes v0.4.12
   Compiling rand_core v0.5.1
   Compiling inotify v0.7.1
   Compiling mio v0.6.23
   Compiling cc v1.0.73
   Compiling sass-sys v0.4.22
   Compiling block-buffer v0.7.3
   Compiling digest v0.8.1
   Compiling crypto-common v0.1.6
   Compiling block-buffer v0.10.2
   Compiling url v2.2.2
   Compiling ctrlc v3.2.2
   Compiling phf v0.11.1
   Compiling crossbeam-deque v0.8.2
   Compiling parse-zoneinfo v0.3.0
   Compiling nom_locate v1.0.0
   Compiling nom_locate v2.1.0
   Compiling svg_metadata v0.4.2
   Compiling chrono v0.4.22
   Compiling rand_chacha v0.3.1
   Compiling rand_chacha v0.2.2
   Compiling mio-extras v2.0.6
   Compiling ring v0.16.20
   Compiling onig_sys v69.8.1
   Compiling libwebp-sys v0.4.2
   Compiling sha-1 v0.8.2
   Compiling digest v0.10.3
   Compiling gh-emoji v1.0.7
   Compiling tokio-util v0.7.3
   Compiling rand v0.8.5
   Compiling rand v0.7.3
   Compiling notify v4.0.17
```
So - after so many failed attempts - I am giving up - but I still am wanting a DEB for the arm64 architecture.... So I am still hoping that someone out there can make it . 🙏🏻🤷🏻‍♂️
