### ISSUE TITLE
Submission to Offical Debian Repos

### ISSUE THREAD

**Issue by c-git** [barnumbirr/zola-debian#3]
Have you explored getting zola added to the official Debian repos so users would be able to just use `sudo apt-get install zola` to install?

I'm looking into it right now and don't want to duplicate effort so checking if you have already looked into it.

**Comment by barnumbirr** [comment]
I haven't as Debian packaging is a mess but someone's close: https://salsa.debian.org/debian/zola

**Comment by c-git** [comment]
Thank you appreciate the information. I'm not a Debian developer and would have had to try to look for a sponsor so really appreciate you saving me the time.
