### ISSUE TITLE
Add package to Debian

### ISSUE THREAD

**Issue by arunkd13** [barnumbirr/zola-debian#5]
I was wondering if this can be added to the Debian distribution so that everyone can just 'apt install' zola.

The official guidelines for adding a package are here: https://www.debian.org/doc/manuals/distribute-deb/distribute-deb.html#adding-packages-to-debian

Has this already been attempted?

**Comment by jalsco** [comment]
@arunkd13 , that would be awesome 🙏🏻

Closed issue  https://github.com/barnumbirr/zola-debian/issues/3

My own attempts to build it for ARM - failed after a dozen (or more) attempts and with environment adjustments each time. 
see (closed) issue # 2 .

**Comment by barnumbirr** [comment]
I somehow missed this issue. Efforts have been started a while ago to officially package `zola` but there are still quite a few upstream dependencies (crates) missing: https://salsa.debian.org/debian/zola
